package com.github.alexthe666.iceandfire.config;

import com.github.alexthe666.citadel.config.biome.BiomeEntryType;
import com.github.alexthe666.citadel.config.biome.SpawnBiomeData;
import net.minecraft.tags.BiomeTags;
import net.neoforge.common.Tags.Biomes;

public class DefaultBiomes {
   public static final SpawnBiomeData OVERWORLD;
   public static final SpawnBiomeData FIREDRAGON_ROOST;
   public static final SpawnBiomeData FIREDRAGON_CAVE;
   public static final SpawnBiomeData ICEDRAGON_ROOST;
   public static final SpawnBiomeData ICEDRAGON_CAVE;
   public static final SpawnBiomeData LIGHTNING_ROOST;
   public static final SpawnBiomeData LIGHTNING_CAVE;
   public static final SpawnBiomeData VERY_HOT;
   public static final SpawnBiomeData VERY_SNOWY;
   public static final SpawnBiomeData MAUSOLEUM;
   public static final SpawnBiomeData SNOWY;
   public static final SpawnBiomeData VERY_HILLY;
   public static final SpawnBiomeData WOODLAND;
   public static final SpawnBiomeData SAVANNAS;
   public static final SpawnBiomeData BEACHES;
   public static final SpawnBiomeData SWAMPS;
   public static final SpawnBiomeData DESERT;
   public static final SpawnBiomeData OCEANS;
   public static final SpawnBiomeData PIXIES;
   public static final SpawnBiomeData JUNGLE;
   public static final SpawnBiomeData HILLS;
   public static final SpawnBiomeData PLAINS;
   public static final SpawnBiomeData GRAVEYARD;
   public static final SpawnBiomeData HIPPOGRYPH_BLACK;
   public static final SpawnBiomeData HIPPOGRYPH_DARK_BROWN;
   public static final SpawnBiomeData HIPPOGRYPH_WHITE;
   public static final SpawnBiomeData HIPPOGRYPH_GRAY;
   public static final SpawnBiomeData HIPPOGRYPH_CHESTNUT;
   public static final SpawnBiomeData HIPPOGRYPH_CREAMY;

   static {
      OVERWORLD = (new SpawnBiomeData()).addBiomeEntry(BiomeEntryType.BIOME_TAG, false, BiomeTags.f_215817_.f_203868_().toString(), 0);
      FIREDRAGON_ROOST = (new SpawnBiomeData()).addBiomeEntry(BiomeEntryType.BIOME_TAG, false, Biomes.IS_HOT_OVERWORLD.f_203868_().toString(), 0).addBiomeEntry(BiomeEntryType.BIOME_TAG, true, BiomeTags.f_207610_.f_203868_().toString(), 0).addBiomeEntry(BiomeEntryType.BIOME_TAG, true, BiomeTags.f_207607_.f_203868_().toString(), 0).addBiomeEntry(BiomeEntryType.BIOME_TAG, true, BiomeTags.f_215816_.f_203868_().toString(), 0).addBiomeEntry(BiomeEntryType.BIOME_TAG, false, BiomeTags.f_215817_.f_203868_().toString(), 1).addBiomeEntry(BiomeEntryType.BIOME_TAG, false, Biomes.IS_PLAINS.f_203868_().toString(), 1).addBiomeEntry(BiomeEntryType.BIOME_TAG, true, Biomes.IS_WET_OVERWORLD.f_203868_().toString(), 1).addBiomeEntry(BiomeEntryType.BIOME_TAG, true, Biomes.IS_COLD_OVERWORLD.f_203868_().toString(), 1).addBiomeEntry(BiomeEntryType.BIOME_TAG, true, BiomeTags.f_207610_.f_203868_().toString(), 1).addBiomeEntry(BiomeEntryType.BIOME_TAG, true, BiomeTags.f_207607_.f_203868_().toString(), 1).addBiomeEntry(BiomeEntryType.BIOME_TAG, true, BiomeTags.f_215816_.f_203868_().toString(), 1).addBiomeEntry(BiomeEntryType.BIOME_TAG, true, BiomeTags.f_207611_.f_203868_().toString(), 1).addBiomeEntry(BiomeEntryType.REGISTRY_NAME, false, "terralith:steppe", 2).addBiomeEntry(BiomeEntryType.REGISTRY_NAME, false, "byg:rose_fields", 3).addBiomeEntry(BiomeEntryType.REGISTRY_NAME, false, "byg:prairie", 4).addBiomeEntry(BiomeEntryType.REGISTRY_NAME, false, "byg:firecracker_shrubland", 5).addBiomeEntry(BiomeEntryType.REGISTRY_NAME, false, "byg:autumnal_valley", 6).addBiomeEntry(BiomeEntryType.REGISTRY_NAME, false, "byg:lush_stacks", 7);
      FIREDRAGON_CAVE = FIREDRAGON_ROOST;
      ICEDRAGON_ROOST = (new SpawnBiomeData()).addBiomeEntry(BiomeEntryType.BIOME_TAG, false, Biomes.IS_COLD_OVERWORLD.f_203868_().toString(), 0).addBiomeEntry(BiomeEntryType.REGISTRY_NAME, false, "byg:shattered_glacier", 1).addBiomeEntry(BiomeEntryType.REGISTRY_NAME, false, "byg:frosted_taiga", 2).addBiomeEntry(BiomeEntryType.REGISTRY_NAME, false, "byg:frosted_coniferous_forest", 3);
      ICEDRAGON_CAVE = ICEDRAGON_ROOST;
      LIGHTNING_ROOST = (new SpawnBiomeData()).addBiomeEntry(BiomeEntryType.BIOME_TAG, false, BiomeTags.f_215817_.f_203868_().toString(), 0).addBiomeEntry(BiomeEntryType.BIOME_TAG, false, BiomeTags.f_207610_.f_203868_().toString(), 0).addBiomeEntry(BiomeEntryType.BIOME_TAG, false, BiomeTags.f_215817_.f_203868_().toString(), 1).addBiomeEntry(BiomeEntryType.BIOME_TAG, false, BiomeTags.f_207607_.f_203868_().toString(), 1).addBiomeEntry(BiomeEntryType.BIOME_TAG, false, BiomeTags.f_215817_.f_203868_().toString(), 2).addBiomeEntry(BiomeEntryType.BIOME_TAG, false, BiomeTags.f_215816_.f_203868_().toString(), 2).addBiomeEntry(BiomeEntryType.REGISTRY_NAME, false, "terralith:ashen_savanna", 3).addBiomeEntry(BiomeEntryType.REGISTRY_NAME, false, "terralith:savanna_badlands", 4).addBiomeEntry(BiomeEntryType.REGISTRY_NAME, false, "terralith:savanna_slopes", 5).addBiomeEntry(BiomeEntryType.REGISTRY_NAME, false, "byg:guiana_shield", 6).addBiomeEntry(BiomeEntryType.REGISTRY_NAME, false, "byg:temperate_rainforest", 7).addBiomeEntry(BiomeEntryType.REGISTRY_NAME, false, "byg:tropical_rainforest", 8).addBiomeEntry(BiomeEntryType.REGISTRY_NAME, false, "byg:jacaranda_forest", 8).addBiomeEntry(BiomeEntryType.REGISTRY_NAME, false, "byg:sierra_badlands", 9);
      LIGHTNING_CAVE = LIGHTNING_ROOST;
      VERY_HOT = (new SpawnBiomeData()).addBiomeEntry(BiomeEntryType.BIOME_TAG, false, Biomes.IS_HOT_OVERWORLD.f_203868_().toString(), 0).addBiomeEntry(BiomeEntryType.REGISTRY_NAME, false, "byg:firecracker_shrubland", 1);
      VERY_SNOWY = (new SpawnBiomeData()).addBiomeEntry(BiomeEntryType.BIOME_TAG, false, BiomeTags.f_215817_.f_203868_().toString(), 0).addBiomeEntry(BiomeEntryType.BIOME_TAG, false, Biomes.IS_SNOWY.f_203868_().toString(), 0).addBiomeEntry(BiomeEntryType.BIOME_TAG, true, Biomes.IS_WET_OVERWORLD.f_203868_().toString(), 0).addBiomeEntry(BiomeEntryType.REGISTRY_NAME, false, "terralith:wintry_forest", 1).addBiomeEntry(BiomeEntryType.REGISTRY_NAME, false, "terralith:wintry_lowlands", 2);
      MAUSOLEUM = (new SpawnBiomeData()).addBiomeEntry(BiomeEntryType.BIOME_TAG, false, BiomeTags.f_215817_.f_203868_().toString(), 0).addBiomeEntry(BiomeEntryType.BIOME_TAG, false, Biomes.IS_SNOWY.f_203868_().toString(), 0).addBiomeEntry(BiomeEntryType.BIOME_TAG, true, Biomes.IS_WET_OVERWORLD.f_203868_().toString(), 0).addBiomeEntry(BiomeEntryType.BIOME_TAG, true, Biomes.IS_WATER.f_203868_().toString(), 0).addBiomeEntry(BiomeEntryType.REGISTRY_NAME, false, "terralith:wintry_forest", 1).addBiomeEntry(BiomeEntryType.REGISTRY_NAME, false, "terralith:wintry_lowlands", 2);
      SNOWY = (new SpawnBiomeData()).addBiomeEntry(BiomeEntryType.BIOME_TAG, false, BiomeTags.f_215817_.f_203868_().toString(), 0).addBiomeEntry(BiomeEntryType.BIOME_TAG, false, Biomes.IS_SNOWY.f_203868_().toString(), 0);
      VERY_HILLY = (new SpawnBiomeData()).addBiomeEntry(BiomeEntryType.BIOME_TAG, false, BiomeTags.f_215817_.f_203868_().toString(), 0).addBiomeEntry(BiomeEntryType.BIOME_TAG, false, Biomes.IS_MOUNTAIN.f_203868_().toString(), 0).addBiomeEntry(BiomeEntryType.BIOME_TAG, false, BiomeTags.f_215817_.f_203868_().toString(), 1).addBiomeEntry(BiomeEntryType.BIOME_TAG, false, BiomeTags.f_207608_.f_203868_().toString(), 1);
      WOODLAND = (new SpawnBiomeData()).addBiomeEntry(BiomeEntryType.BIOME_TAG, false, BiomeTags.f_215817_.f_203868_().toString(), 0).addBiomeEntry(BiomeEntryType.BIOME_TAG, false, BiomeTags.f_207611_.f_203868_().toString(), 0);
      SAVANNAS = (new SpawnBiomeData()).addBiomeEntry(BiomeEntryType.BIOME_TAG, false, BiomeTags.f_215817_.f_203868_().toString(), 0).addBiomeEntry(BiomeEntryType.BIOME_TAG, false, BiomeTags.f_215816_.f_203868_().toString(), 0).addBiomeEntry(BiomeEntryType.REGISTRY_NAME, false, "terralith:fractured_savanna", 1).addBiomeEntry(BiomeEntryType.REGISTRY_NAME, false, "terralith:savanna_badlands", 2).addBiomeEntry(BiomeEntryType.REGISTRY_NAME, false, "terralith:savanna_slopes", 3).addBiomeEntry(BiomeEntryType.REGISTRY_NAME, false, "byg:baobab_savanna", 4).addBiomeEntry(BiomeEntryType.REGISTRY_NAME, false, "byg:araucaria_savanna", 5);
      BEACHES = (new SpawnBiomeData()).addBiomeEntry(BiomeEntryType.BIOME_TAG, false, BiomeTags.f_215817_.f_203868_().toString(), 0).addBiomeEntry(BiomeEntryType.BIOME_TAG, false, BiomeTags.f_207604_.f_203868_().toString(), 0).addBiomeEntry(BiomeEntryType.BIOME_TAG, true, BiomeTags.f_207603_.f_203868_().toString(), 0).addBiomeEntry(BiomeEntryType.REGISTRY_NAME, false, "byg:dacite_shore", 1).addBiomeEntry(BiomeEntryType.REGISTRY_NAME, false, "byg:basalt_barrera", 2);
      SWAMPS = (new SpawnBiomeData()).addBiomeEntry(BiomeEntryType.BIOME_TAG, false, BiomeTags.f_215817_.f_203868_().toString(), 0).addBiomeEntry(BiomeEntryType.BIOME_TAG, false, Biomes.IS_SWAMP.f_203868_().toString(), 0).addBiomeEntry(BiomeEntryType.REGISTRY_NAME, false, "terralith:orchid_swamp", 1).addBiomeEntry(BiomeEntryType.REGISTRY_NAME, false, "byg:crag_gardens", 2).addBiomeEntry(BiomeEntryType.REGISTRY_NAME, false, "byg:cypress_swamplands", 3).addBiomeEntry(BiomeEntryType.REGISTRY_NAME, false, "byg:bayou", 4);
      DESERT = (new SpawnBiomeData()).addBiomeEntry(BiomeEntryType.BIOME_TAG, false, Biomes.IS_DRY_OVERWORLD.f_203868_().toString(), 0).addBiomeEntry(BiomeEntryType.BIOME_TAG, false, Biomes.IS_HOT_OVERWORLD.f_203868_().toString(), 0).addBiomeEntry(BiomeEntryType.BIOME_TAG, false, Biomes.IS_SANDY.f_203868_().toString(), 0).addBiomeEntry(BiomeEntryType.BIOME_TAG, true, BiomeTags.f_207607_.f_203868_().toString(), 0).addBiomeEntry(BiomeEntryType.REGISTRY_NAME, false, "terralith:desert_canyon", 1).addBiomeEntry(BiomeEntryType.REGISTRY_NAME, false, "terralith:desert_oasis", 2).addBiomeEntry(BiomeEntryType.REGISTRY_NAME, false, "terralith:desert_spires", 3).addBiomeEntry(BiomeEntryType.REGISTRY_NAME, false, "terralith:ancient_sands", 4).addBiomeEntry(BiomeEntryType.REGISTRY_NAME, false, "byg:mojave_desert", 5).addBiomeEntry(BiomeEntryType.REGISTRY_NAME, false, "byg:atacama_desert", 6).addBiomeEntry(BiomeEntryType.REGISTRY_NAME, false, "byg:windswept_valley", 7);
      OCEANS = (new SpawnBiomeData()).addBiomeEntry(BiomeEntryType.BIOME_TAG, false, BiomeTags.f_215817_.f_203868_().toString(), 0).addBiomeEntry(BiomeEntryType.BIOME_TAG, false, BiomeTags.f_207603_.f_203868_().toString(), 0);
      PIXIES = (new SpawnBiomeData()).addBiomeEntry(BiomeEntryType.BIOME_TAG, false, BiomeTags.f_215817_.f_203868_().toString(), 0).addBiomeEntry(BiomeEntryType.BIOME_TAG, false, Biomes.IS_RARE.f_203868_().toString(), 0).addBiomeEntry(BiomeEntryType.BIOME_TAG, false, Biomes.IS_MAGICAL.f_203868_().toString(), 0).addBiomeEntry(BiomeEntryType.BIOME_TAG, false, BiomeTags.f_215817_.f_203868_().toString(), 1).addBiomeEntry(BiomeEntryType.BIOME_TAG, false, Biomes.IS_DENSE.f_203868_().toString(), 1).addBiomeEntry(BiomeEntryType.BIOME_TAG, false, BiomeTags.f_207611_.f_203868_().toString(), 1).addBiomeEntry(BiomeEntryType.BIOME_TAG, true, Biomes.IS_MOUNTAIN.f_203868_().toString(), 1).addBiomeEntry(BiomeEntryType.BIOME_TAG, true, BiomeTags.f_207608_.f_203868_().toString(), 1).addBiomeEntry(BiomeEntryType.BIOME_TAG, true, Biomes.IS_WET_OVERWORLD.f_203868_().toString(), 1).addBiomeEntry(BiomeEntryType.BIOME_TAG, true, Biomes.IS_HOT.f_203868_().toString(), 1).addBiomeEntry(BiomeEntryType.BIOME_TAG, true, Biomes.IS_COLD.f_203868_().toString(), 1).addBiomeEntry(BiomeEntryType.BIOME_TAG, true, Biomes.IS_DRY.f_203868_().toString(), 1).addBiomeEntry(BiomeEntryType.BIOME_TAG, true, BiomeTags.f_207609_.f_203868_().toString(), 1).addBiomeEntry(BiomeEntryType.REGISTRY_NAME, false, "terralith:siberian_taiga", 2).addBiomeEntry(BiomeEntryType.REGISTRY_NAME, false, "terralith:skylands", 3).addBiomeEntry(BiomeEntryType.REGISTRY_NAME, false, "terralith:mirage_isles", 4).addBiomeEntry(BiomeEntryType.REGISTRY_NAME, false, "byg:amaranth_fields", 5).addBiomeEntry(BiomeEntryType.REGISTRY_NAME, false, "byg:skyris_vale", 6).addBiomeEntry(BiomeEntryType.REGISTRY_NAME, false, "byg:rainbow_beach", 7);
      JUNGLE = (new SpawnBiomeData()).addBiomeEntry(BiomeEntryType.BIOME_TAG, false, BiomeTags.f_215817_.f_203868_().toString(), 0).addBiomeEntry(BiomeEntryType.BIOME_TAG, false, BiomeTags.f_207610_.f_203868_().toString(), 0).addBiomeEntry(BiomeEntryType.REGISTRY_NAME, false, "byg:guiana_shield", 1).addBiomeEntry(BiomeEntryType.REGISTRY_NAME, false, "byg:temperate_rainforest", 2).addBiomeEntry(BiomeEntryType.REGISTRY_NAME, false, "byg:tropical_rainforest", 3).addBiomeEntry(BiomeEntryType.REGISTRY_NAME, false, "byg:jacaranda_forest", 4);
      HILLS = (new SpawnBiomeData()).addBiomeEntry(BiomeEntryType.BIOME_TAG, false, BiomeTags.f_215817_.f_203868_().toString(), 0).addBiomeEntry(BiomeEntryType.BIOME_TAG, false, BiomeTags.f_207607_.f_203868_().toString(), 0).addBiomeEntry(BiomeEntryType.BIOME_TAG, false, BiomeTags.f_215817_.f_203868_().toString(), 1).addBiomeEntry(BiomeEntryType.BIOME_TAG, false, Biomes.IS_MOUNTAIN.f_203868_().toString(), 1).addBiomeEntry(BiomeEntryType.BIOME_TAG, false, BiomeTags.f_215817_.f_203868_().toString(), 2).addBiomeEntry(BiomeEntryType.BIOME_TAG, false, BiomeTags.f_207608_.f_203868_().toString(), 2).addBiomeEntry(BiomeEntryType.REGISTRY_NAME, false, "terralith:rocky_mountains", 3);
      PLAINS = (new SpawnBiomeData()).addBiomeEntry(BiomeEntryType.BIOME_TAG, false, BiomeTags.f_215817_.f_203868_().toString(), 0).addBiomeEntry(BiomeEntryType.BIOME_TAG, false, Biomes.IS_PLAINS.f_203868_().toString(), 0).addBiomeEntry(BiomeEntryType.REGISTRY_NAME, false, "terralith:steppe", 1).addBiomeEntry(BiomeEntryType.REGISTRY_NAME, false, "byg:firecracker_shrubland", 2).addBiomeEntry(BiomeEntryType.REGISTRY_NAME, false, "byg:autumnal_valley", 3);
      GRAVEYARD = (new SpawnBiomeData()).addBiomeEntry(BiomeEntryType.BIOME_TAG, false, BiomeTags.f_215817_.f_203868_().toString(), 0).addBiomeEntry(BiomeEntryType.BIOME_TAG, true, Biomes.IS_WATER.f_203868_().toString(), 0).addBiomeEntry(BiomeEntryType.BIOME_TAG, true, BiomeTags.f_207604_.f_203868_().toString(), 0).addBiomeEntry(BiomeEntryType.BIOME_TAG, true, Biomes.IS_UNDERGROUND.f_203868_().toString(), 0);
      HIPPOGRYPH_BLACK = (new SpawnBiomeData()).addBiomeEntry(BiomeEntryType.REGISTRY_NAME, false, "minecraft:badlands", 0).addBiomeEntry(BiomeEntryType.REGISTRY_NAME, false, "terralith:painted_mountains", 1);
      HIPPOGRYPH_DARK_BROWN = (new SpawnBiomeData()).addBiomeEntry(BiomeEntryType.BIOME_TAG, false, BiomeTags.f_215817_.f_203868_().toString(), 0).addBiomeEntry(BiomeEntryType.BIOME_TAG, false, BiomeTags.f_207611_.f_203868_().toString(), 0).addBiomeEntry(BiomeEntryType.BIOME_TAG, false, Biomes.IS_MOUNTAIN.f_203868_().toString(), 0).addBiomeEntry(BiomeEntryType.BIOME_TAG, false, Biomes.IS_SNOWY.f_203868_().toString(), 0).addBiomeEntry(BiomeEntryType.BIOME_TAG, false, BiomeTags.f_215817_.f_203868_().toString(), 1).addBiomeEntry(BiomeEntryType.BIOME_TAG, false, BiomeTags.f_207611_.f_203868_().toString(), 1).addBiomeEntry(BiomeEntryType.BIOME_TAG, false, BiomeTags.f_207608_.f_203868_().toString(), 1).addBiomeEntry(BiomeEntryType.BIOME_TAG, false, Biomes.IS_SNOWY.f_203868_().toString(), 1).addBiomeEntry(BiomeEntryType.REGISTRY_NAME, false, "terralith:scarlet_mountains", 2);
      HIPPOGRYPH_WHITE = (new SpawnBiomeData()).addBiomeEntry(BiomeEntryType.BIOME_TAG, false, BiomeTags.f_215817_.f_203868_().toString(), 0).addBiomeEntry(BiomeEntryType.BIOME_TAG, false, Biomes.IS_SPARSE.f_203868_().toString(), 0).addBiomeEntry(BiomeEntryType.BIOME_TAG, false, Biomes.IS_SNOWY.f_203868_().toString(), 0).addBiomeEntry(BiomeEntryType.BIOME_TAG, false, Biomes.IS_MOUNTAIN.f_203868_().toString(), 0).addBiomeEntry(BiomeEntryType.BIOME_TAG, false, Biomes.IS_PEAK.f_203868_().toString(), 0).addBiomeEntry(BiomeEntryType.BIOME_TAG, false, BiomeTags.f_215817_.f_203868_().toString(), 1).addBiomeEntry(BiomeEntryType.BIOME_TAG, false, Biomes.IS_SPARSE.f_203868_().toString(), 1).addBiomeEntry(BiomeEntryType.BIOME_TAG, false, Biomes.IS_SNOWY.f_203868_().toString(), 1).addBiomeEntry(BiomeEntryType.BIOME_TAG, false, Biomes.IS_MOUNTAIN.f_203868_().toString(), 1).addBiomeEntry(BiomeEntryType.BIOME_TAG, false, Biomes.IS_SLOPE.f_203868_().toString(), 1).addBiomeEntry(BiomeEntryType.REGISTRY_NAME, false, "terralith:rocky_mountains", 2);
      HIPPOGRYPH_GRAY = (new SpawnBiomeData()).addBiomeEntry(BiomeEntryType.REGISTRY_NAME, false, "minecraft:windswept_forest", 0).addBiomeEntry(BiomeEntryType.REGISTRY_NAME, false, "minecraft:windswept_hills", 1).addBiomeEntry(BiomeEntryType.REGISTRY_NAME, false, "terralith:windswept_spires", 2);
      HIPPOGRYPH_CHESTNUT = (new SpawnBiomeData()).addBiomeEntry(BiomeEntryType.BIOME_TAG, false, BiomeTags.f_215817_.f_203868_().toString(), 0).addBiomeEntry(BiomeEntryType.BIOME_TAG, false, Biomes.IS_MOUNTAIN.f_203868_().toString(), 0).addBiomeEntry(BiomeEntryType.BIOME_TAG, false, BiomeTags.f_207607_.f_203868_().toString(), 0).addBiomeEntry(BiomeEntryType.BIOME_TAG, false, Biomes.IS_DRY.f_203868_().toString(), 0).addBiomeEntry(BiomeEntryType.REGISTRY_NAME, false, "terralith:savanna_badlands", 1);
      HIPPOGRYPH_CREAMY = (new SpawnBiomeData()).addBiomeEntry(BiomeEntryType.REGISTRY_NAME, false, "minecraft:savanna_plateau", 0).addBiomeEntry(BiomeEntryType.REGISTRY_NAME, false, "terralith:fractured_savanna", 1);
   }
}
